services:
  app:
    image: node:20.18-alpine
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: root_password
    volumes:
      # - postgres:/var/lib/postgresql/data
      - ./build/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql